# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola-dolby/dolby/setup-makefiles.sh

# HIDL
DEVICE_MANIFEST_FILE += $(CONFIG_PATH)/hidl/manifest.xml
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += $(CONFIG_PATH)/hidl/framework_compatibility_matrix.xml
